const MOVIES = {
  LOAD: "MOVIES_LOAD",
  LOAD_SUCCESS: "MOVIES_LOAD_SUCCESS",
  LOAD_FAIL: "MOVIES_LOAD_FAIL",
  LOAD_DETAILS: "MOVIES_LOAD_DETAILS",
  LOAD_DETAILS_SUCCESS: "MOVIES_LOAD_DETAILS_SUCCESS"
};

export { MOVIES };
